// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestGetEventByIdQueryParameters_Validate(t *testing.T) {
	tests := []struct {
		name      string
		m         GetEventByIdQueryParameters
		assertion assert.ErrorAssertionFunc
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.assertion(t, tt.m.Validate())
		})
	}
}

func TestGetEventByIdQueryParameters_GetEventId(t *testing.T) {
	tests := []struct {
		name string
		m    GetEventByIdQueryParameters
		want int64
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.m.GetEventId())
		})
	}
}

func TestGetEventByIdQueryParameters_SetEventId(t *testing.T) {
	type args struct {
		val int64
	}
	tests := []struct {
		name string
		m    *GetEventByIdQueryParameters
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.m.SetEventId(tt.args.val)
		})
	}
}
