// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// FindFarmByNameQueryParameters is an object.
type FindFarmByNameQueryParameters struct {
	// Name: String for farm name
	Name string `json:"name,omitempty" mapstructure:"name,omitempty"`
}

// Validate implements basic validation for this model
func (m FindFarmByNameQueryParameters) Validate() error {
	return validation.Errors{}.Filter()
}

// GetName returns the Name property
func (m FindFarmByNameQueryParameters) GetName() string {
	return m.Name
}

// SetName sets the Name property
func (m *FindFarmByNameQueryParameters) SetName(val string) {
	m.Name = val
}
