// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// DeleteFarmQueryParameters is an object.
type DeleteFarmQueryParameters struct {
	// ApiKey:
	ApiKey string `json:"api_key,omitempty" mapstructure:"api_key,omitempty"`
	// FarmId: Farm id to delete
	FarmId int64 `json:"farmId" mapstructure:"farmId"`
}

// Validate implements basic validation for this model
func (m DeleteFarmQueryParameters) Validate() error {
	return validation.Errors{}.Filter()
}

// GetApiKey returns the ApiKey property
func (m DeleteFarmQueryParameters) GetApiKey() string {
	return m.ApiKey
}

// SetApiKey sets the ApiKey property
func (m *DeleteFarmQueryParameters) SetApiKey(val string) {
	m.ApiKey = val
}

// GetFarmId returns the FarmId property
func (m DeleteFarmQueryParameters) GetFarmId() int64 {
	return m.FarmId
}

// SetFarmId sets the FarmId property
func (m *DeleteFarmQueryParameters) SetFarmId(val int64) {
	m.FarmId = val
}
