// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// GetDeviceByIdQueryParameters is an object.
type GetDeviceByIdQueryParameters struct {
	// DeviceId: id of device to return
	DeviceId int64 `json:"deviceId" mapstructure:"deviceId"`
}

// Validate implements basic validation for this model
func (m GetDeviceByIdQueryParameters) Validate() error {
	return validation.Errors{}.Filter()
}

// GetDeviceId returns the DeviceId property
func (m GetDeviceByIdQueryParameters) GetDeviceId() int64 {
	return m.DeviceId
}

// SetDeviceId sets the DeviceId property
func (m *GetDeviceByIdQueryParameters) SetDeviceId(val int64) {
	m.DeviceId = val
}
