// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestPersonAssociation_Validate(t *testing.T) {
	tests := []struct {
		name      string
		m         PersonAssociation
		assertion assert.ErrorAssertionFunc
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.assertion(t, tt.m.Validate())
		})
	}
}

func TestPersonAssociation_GetDisplayName(t *testing.T) {
	tests := []struct {
		name string
		m    PersonAssociation
		want string
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.m.GetDisplayName())
		})
	}
}

func TestPersonAssociation_SetDisplayName(t *testing.T) {
	type args struct {
		val string
	}
	tests := []struct {
		name string
		m    *PersonAssociation
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.m.SetDisplayName(tt.args.val)
		})
	}
}

func TestPersonAssociation_GetEmail(t *testing.T) {
	tests := []struct {
		name string
		m    PersonAssociation
		want string
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.m.GetEmail())
		})
	}
}

func TestPersonAssociation_SetEmail(t *testing.T) {
	type args struct {
		val string
	}
	tests := []struct {
		name string
		m    *PersonAssociation
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.m.SetEmail(tt.args.val)
		})
	}
}

func TestPersonAssociation_GetPersonId(t *testing.T) {
	tests := []struct {
		name string
		m    PersonAssociation
		want int64
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.m.GetPersonId())
		})
	}
}

func TestPersonAssociation_SetPersonId(t *testing.T) {
	type args struct {
		val int64
	}
	tests := []struct {
		name string
		m    *PersonAssociation
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.m.SetPersonId(tt.args.val)
		})
	}
}

func TestPersonAssociation_GetRole(t *testing.T) {
	tests := []struct {
		name string
		m    PersonAssociation
		want Role
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.m.GetRole())
		})
	}
}

func TestPersonAssociation_SetRole(t *testing.T) {
	type args struct {
		val Role
	}
	tests := []struct {
		name string
		m    *PersonAssociation
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.m.SetRole(tt.args.val)
		})
	}
}
