// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// Person is an object.
type Person struct {
	// DisplayName:
	DisplayName string `json:"displayName,omitempty" mapstructure:"displayName,omitempty"`
	// Email:
	Email string `json:"email,omitempty" mapstructure:"email,omitempty"`
	// FarmAssociations:
	FarmAssociations []FarmAssociation `json:"farmAssociations,omitempty" mapstructure:"farmAssociations,omitempty"`
	// FirstName:
	FirstName string `json:"firstName,omitempty" mapstructure:"firstName,omitempty"`
	// Id:
	Id int64 `json:"id,omitempty" mapstructure:"id,omitempty"`
	// Kind:
	Kind string `json:"kind,omitempty" mapstructure:"kind,omitempty"`
	// LastName:
	LastName string `json:"lastName,omitempty" mapstructure:"lastName,omitempty"`
	// Phone:
	Phone string `json:"phone,omitempty" mapstructure:"phone,omitempty"`
}

// Validate implements basic validation for this model
func (m Person) Validate() error {
	return validation.Errors{
		"farmAssociations": validation.Validate(
			m.FarmAssociations,
		),
	}.Filter()
}

// GetDisplayName returns the DisplayName property
func (m Person) GetDisplayName() string {
	return m.DisplayName
}

// SetDisplayName sets the DisplayName property
func (m *Person) SetDisplayName(val string) {
	m.DisplayName = val
}

// GetEmail returns the Email property
func (m Person) GetEmail() string {
	return m.Email
}

// SetEmail sets the Email property
func (m *Person) SetEmail(val string) {
	m.Email = val
}

// GetFarmAssociations returns the FarmAssociations property
func (m Person) GetFarmAssociations() []FarmAssociation {
	return m.FarmAssociations
}

// SetFarmAssociations sets the FarmAssociations property
func (m *Person) SetFarmAssociations(val []FarmAssociation) {
	m.FarmAssociations = val
}

// GetFirstName returns the FirstName property
func (m Person) GetFirstName() string {
	return m.FirstName
}

// SetFirstName sets the FirstName property
func (m *Person) SetFirstName(val string) {
	m.FirstName = val
}

// GetId returns the Id property
func (m Person) GetId() int64 {
	return m.Id
}

// SetId sets the Id property
func (m *Person) SetId(val int64) {
	m.Id = val
}

// GetKind returns the Kind property
func (m Person) GetKind() string {
	return m.Kind
}

// SetKind sets the Kind property
func (m *Person) SetKind(val string) {
	m.Kind = val
}

// GetLastName returns the LastName property
func (m Person) GetLastName() string {
	return m.LastName
}

// SetLastName sets the LastName property
func (m *Person) SetLastName(val string) {
	m.LastName = val
}

// GetPhone returns the Phone property
func (m Person) GetPhone() string {
	return m.Phone
}

// SetPhone sets the Phone property
func (m *Person) SetPhone(val string) {
	m.Phone = val
}
