// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// DeleteTunnelQueryParameters is an object.
type DeleteTunnelQueryParameters struct {
	// ApiKey:
	ApiKey string `json:"api_key,omitempty" mapstructure:"api_key,omitempty"`
	// TunnelId: Tunnel id to delete
	TunnelId int64 `json:"tunnelId" mapstructure:"tunnelId"`
}

// Validate implements basic validation for this model
func (m DeleteTunnelQueryParameters) Validate() error {
	return validation.Errors{}.Filter()
}

// GetApiKey returns the ApiKey property
func (m DeleteTunnelQueryParameters) GetApiKey() string {
	return m.ApiKey
}

// SetApiKey sets the ApiKey property
func (m *DeleteTunnelQueryParameters) SetApiKey(val string) {
	m.ApiKey = val
}

// GetTunnelId returns the TunnelId property
func (m DeleteTunnelQueryParameters) GetTunnelId() int64 {
	return m.TunnelId
}

// SetTunnelId sets the TunnelId property
func (m *DeleteTunnelQueryParameters) SetTunnelId(val int64) {
	m.TunnelId = val
}
