// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// AddPersonQueryParameters is an object.
type AddPersonQueryParameters struct {
	// FarmId: id of farm to return
	FarmId int64 `json:"farmId" mapstructure:"farmId"`
}

// Validate implements basic validation for this model
func (m AddPersonQueryParameters) Validate() error {
	return validation.Errors{}.Filter()
}

// GetFarmId returns the FarmId property
func (m AddPersonQueryParameters) GetFarmId() int64 {
	return m.FarmId
}

// SetFarmId sets the FarmId property
func (m *AddPersonQueryParameters) SetFarmId(val int64) {
	m.FarmId = val
}
