// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// GetPersonByIdQueryParameters is an object.
type GetPersonByIdQueryParameters struct {
	// PersonId: id of person to return
	PersonId int64 `json:"personId" mapstructure:"personId"`
}

// Validate implements basic validation for this model
func (m GetPersonByIdQueryParameters) Validate() error {
	return validation.Errors{}.Filter()
}

// GetPersonId returns the PersonId property
func (m GetPersonByIdQueryParameters) GetPersonId() int64 {
	return m.PersonId
}

// SetPersonId sets the PersonId property
func (m *GetPersonByIdQueryParameters) SetPersonId(val int64) {
	m.PersonId = val
}
