// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestPerson_Validate(t *testing.T) {
	tests := []struct {
		name      string
		m         Person
		assertion assert.ErrorAssertionFunc
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.assertion(t, tt.m.Validate())
		})
	}
}

func TestPerson_GetDisplayName(t *testing.T) {
	tests := []struct {
		name string
		m    Person
		want string
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.m.GetDisplayName())
		})
	}
}

func TestPerson_SetDisplayName(t *testing.T) {
	type args struct {
		val string
	}
	tests := []struct {
		name string
		m    *Person
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.m.SetDisplayName(tt.args.val)
		})
	}
}

func TestPerson_GetEmail(t *testing.T) {
	tests := []struct {
		name string
		m    Person
		want string
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.m.GetEmail())
		})
	}
}

func TestPerson_SetEmail(t *testing.T) {
	type args struct {
		val string
	}
	tests := []struct {
		name string
		m    *Person
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.m.SetEmail(tt.args.val)
		})
	}
}

func TestPerson_GetFarmAssociations(t *testing.T) {
	tests := []struct {
		name string
		m    Person
		want []FarmAssociation
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.m.GetFarmAssociations())
		})
	}
}

func TestPerson_SetFarmAssociations(t *testing.T) {
	type args struct {
		val []FarmAssociation
	}
	tests := []struct {
		name string
		m    *Person
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.m.SetFarmAssociations(tt.args.val)
		})
	}
}

func TestPerson_GetFirstName(t *testing.T) {
	tests := []struct {
		name string
		m    Person
		want string
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.m.GetFirstName())
		})
	}
}

func TestPerson_SetFirstName(t *testing.T) {
	type args struct {
		val string
	}
	tests := []struct {
		name string
		m    *Person
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.m.SetFirstName(tt.args.val)
		})
	}
}

func TestPerson_GetId(t *testing.T) {
	tests := []struct {
		name string
		m    Person
		want int64
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.m.GetId())
		})
	}
}

func TestPerson_SetId(t *testing.T) {
	type args struct {
		val int64
	}
	tests := []struct {
		name string
		m    *Person
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.m.SetId(tt.args.val)
		})
	}
}

func TestPerson_GetKind(t *testing.T) {
	tests := []struct {
		name string
		m    Person
		want string
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.m.GetKind())
		})
	}
}

func TestPerson_SetKind(t *testing.T) {
	type args struct {
		val string
	}
	tests := []struct {
		name string
		m    *Person
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.m.SetKind(tt.args.val)
		})
	}
}

func TestPerson_GetLastName(t *testing.T) {
	tests := []struct {
		name string
		m    Person
		want string
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.m.GetLastName())
		})
	}
}

func TestPerson_SetLastName(t *testing.T) {
	type args struct {
		val string
	}
	tests := []struct {
		name string
		m    *Person
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.m.SetLastName(tt.args.val)
		})
	}
}

func TestPerson_GetPhone(t *testing.T) {
	tests := []struct {
		name string
		m    Person
		want string
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.m.GetPhone())
		})
	}
}

func TestPerson_SetPhone(t *testing.T) {
	type args struct {
		val string
	}
	tests := []struct {
		name string
		m    *Person
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.m.SetPhone(tt.args.val)
		})
	}
}
