// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
	"time"
)

// Event is an object.
type Event struct {
	// Date:
	Date time.Time `json:"date,omitempty" mapstructure:"date,omitempty"`
	// Description:
	Description string `json:"description,omitempty" mapstructure:"description,omitempty"`
	// Id:
	Id int64 `json:"id,omitempty" mapstructure:"id,omitempty"`
	// Kind:
	Kind string `json:"kind,omitempty" mapstructure:"kind,omitempty"`
	// Operator:
	Operator string `json:"operator,omitempty" mapstructure:"operator,omitempty"`
}

// Validate implements basic validation for this model
func (m Event) Validate() error {
	return validation.Errors{
		"date": validation.Validate(
			m.Date, validation.Date(time.RFC3339),
		),
	}.Filter()
}

// GetDate returns the Date property
func (m Event) GetDate() time.Time {
	return m.Date
}

// SetDate sets the Date property
func (m *Event) SetDate(val time.Time) {
	m.Date = val
}

// GetDescription returns the Description property
func (m Event) GetDescription() string {
	return m.Description
}

// SetDescription sets the Description property
func (m *Event) SetDescription(val string) {
	m.Description = val
}

// GetId returns the Id property
func (m Event) GetId() int64 {
	return m.Id
}

// SetId sets the Id property
func (m *Event) SetId(val int64) {
	m.Id = val
}

// GetKind returns the Kind property
func (m Event) GetKind() string {
	return m.Kind
}

// SetKind sets the Kind property
func (m *Event) SetKind(val string) {
	m.Kind = val
}

// GetOperator returns the Operator property
func (m Event) GetOperator() string {
	return m.Operator
}

// SetOperator sets the Operator property
func (m *Event) SetOperator(val string) {
	m.Operator = val
}
