// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// PersonAssociation is an object.
type PersonAssociation struct {
	// DisplayName:
	DisplayName string `json:"displayName,omitempty" mapstructure:"displayName,omitempty"`
	// Email:
	Email string `json:"email,omitempty" mapstructure:"email,omitempty"`
	// PersonId:
	PersonId int64 `json:"personId,omitempty" mapstructure:"personId,omitempty"`
	// Role:
	Role Role `json:"role,omitempty" mapstructure:"role,omitempty"`
}

// Validate implements basic validation for this model
func (m PersonAssociation) Validate() error {
	return validation.Errors{
		"role": validation.Validate(
			m.Role,
		),
	}.Filter()
}

// GetDisplayName returns the DisplayName property
func (m PersonAssociation) GetDisplayName() string {
	return m.DisplayName
}

// SetDisplayName sets the DisplayName property
func (m *PersonAssociation) SetDisplayName(val string) {
	m.DisplayName = val
}

// GetEmail returns the Email property
func (m PersonAssociation) GetEmail() string {
	return m.Email
}

// SetEmail sets the Email property
func (m *PersonAssociation) SetEmail(val string) {
	m.Email = val
}

// GetPersonId returns the PersonId property
func (m PersonAssociation) GetPersonId() int64 {
	return m.PersonId
}

// SetPersonId sets the PersonId property
func (m *PersonAssociation) SetPersonId(val int64) {
	m.PersonId = val
}

// GetRole returns the Role property
func (m PersonAssociation) GetRole() Role {
	return m.Role
}

// SetRole sets the Role property
func (m *PersonAssociation) SetRole(val Role) {
	m.Role = val
}
