// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestFindFarmByNameQueryParameters_Validate(t *testing.T) {
	tests := []struct {
		name      string
		m         FindFarmByNameQueryParameters
		assertion assert.ErrorAssertionFunc
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.assertion(t, tt.m.Validate())
		})
	}
}

func TestFindFarmByNameQueryParameters_GetName(t *testing.T) {
	tests := []struct {
		name string
		m    FindFarmByNameQueryParameters
		want string
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.m.GetName())
		})
	}
}

func TestFindFarmByNameQueryParameters_SetName(t *testing.T) {
	type args struct {
		val string
	}
	tests := []struct {
		name string
		m    *FindFarmByNameQueryParameters
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.m.SetName(tt.args.val)
		})
	}
}
