// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
	"time"
)

// Farm is an object.
type Farm struct {
	// Address:
	Address *Address `json:"address,omitempty" mapstructure:"address,omitempty"`
	// CreateDate:
	CreateDate time.Time `json:"createDate,omitempty" mapstructure:"createDate,omitempty"`
	// Id:
	Id int64 `json:"id,omitempty" mapstructure:"id,omitempty"`
	// Kind:
	Kind string `json:"kind,omitempty" mapstructure:"kind,omitempty"`
	// Name:
	Name string `json:"name,omitempty" mapstructure:"name,omitempty"`
	// Owners:
	Owners []PersonAssociation `json:"owners,omitempty" mapstructure:"owners,omitempty"`
	// People:
	People []PersonAssociation `json:"people,omitempty" mapstructure:"people,omitempty"`
}

// Validate implements basic validation for this model
func (m Farm) Validate() error {
	return validation.Errors{
		"address": validation.Validate(
			m.Address,
		),
		"createDate": validation.Validate(
			m.CreateDate, validation.Date(time.RFC3339),
		),
		"owners": validation.Validate(
			m.Owners,
		),
		"people": validation.Validate(
			m.People,
		),
	}.Filter()
}

// GetAddress returns the Address property
func (m Farm) GetAddress() *Address {
	return m.Address
}

// SetAddress sets the Address property
func (m *Farm) SetAddress(val *Address) {
	m.Address = val
}

// GetCreateDate returns the CreateDate property
func (m Farm) GetCreateDate() time.Time {
	return m.CreateDate
}

// SetCreateDate sets the CreateDate property
func (m *Farm) SetCreateDate(val time.Time) {
	m.CreateDate = val
}

// GetId returns the Id property
func (m Farm) GetId() int64 {
	return m.Id
}

// SetId sets the Id property
func (m *Farm) SetId(val int64) {
	m.Id = val
}

// GetKind returns the Kind property
func (m Farm) GetKind() string {
	return m.Kind
}

// SetKind sets the Kind property
func (m *Farm) SetKind(val string) {
	m.Kind = val
}

// GetName returns the Name property
func (m Farm) GetName() string {
	return m.Name
}

// SetName sets the Name property
func (m *Farm) SetName(val string) {
	m.Name = val
}

// GetOwners returns the Owners property
func (m Farm) GetOwners() []PersonAssociation {
	return m.Owners
}

// SetOwners sets the Owners property
func (m *Farm) SetOwners(val []PersonAssociation) {
	m.Owners = val
}

// GetPeople returns the People property
func (m Farm) GetPeople() []PersonAssociation {
	return m.People
}

// SetPeople sets the People property
func (m *Farm) SetPeople(val []PersonAssociation) {
	m.People = val
}
