// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// FarmAssociation is an object.
type FarmAssociation struct {
	// FarmId:
	FarmId int64 `json:"farmId,omitempty" mapstructure:"farmId,omitempty"`
	// FarmName:
	FarmName string `json:"farmName,omitempty" mapstructure:"farmName,omitempty"`
	// Role:
	Role Role `json:"role,omitempty" mapstructure:"role,omitempty"`
}

// Validate implements basic validation for this model
func (m FarmAssociation) Validate() error {
	return validation.Errors{
		"role": validation.Validate(
			m.Role,
		),
	}.Filter()
}

// GetFarmId returns the FarmId property
func (m FarmAssociation) GetFarmId() int64 {
	return m.FarmId
}

// SetFarmId sets the FarmId property
func (m *FarmAssociation) SetFarmId(val int64) {
	m.FarmId = val
}

// GetFarmName returns the FarmName property
func (m FarmAssociation) GetFarmName() string {
	return m.FarmName
}

// SetFarmName sets the FarmName property
func (m *FarmAssociation) SetFarmName(val string) {
	m.FarmName = val
}

// GetRole returns the Role property
func (m FarmAssociation) GetRole() Role {
	return m.Role
}

// SetRole sets the Role property
func (m *FarmAssociation) SetRole(val Role) {
	m.Role = val
}
