// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// Device is an object.
type Device struct {
	// Category:
	Category DeviceCategory `json:"category,omitempty" mapstructure:"category,omitempty"`
	// Id:
	Id int64 `json:"id,omitempty" mapstructure:"id,omitempty"`
	// Kind:
	Kind string `json:"kind,omitempty" mapstructure:"kind,omitempty"`
	// Name:
	Name string `json:"name" mapstructure:"name"`
	// TunnelId:
	TunnelId int64 `json:"tunnelId,omitempty" mapstructure:"tunnelId,omitempty"`
}

// Validate implements basic validation for this model
func (m Device) Validate() error {
	return validation.Errors{
		"category": validation.Validate(
			m.Category,
		),
	}.Filter()
}

// GetCategory returns the Category property
func (m Device) GetCategory() DeviceCategory {
	return m.Category
}

// SetCategory sets the Category property
func (m *Device) SetCategory(val DeviceCategory) {
	m.Category = val
}

// GetId returns the Id property
func (m Device) GetId() int64 {
	return m.Id
}

// SetId sets the Id property
func (m *Device) SetId(val int64) {
	m.Id = val
}

// GetKind returns the Kind property
func (m Device) GetKind() string {
	return m.Kind
}

// SetKind sets the Kind property
func (m *Device) SetKind(val string) {
	m.Kind = val
}

// GetName returns the Name property
func (m Device) GetName() string {
	return m.Name
}

// SetName sets the Name property
func (m *Device) SetName(val string) {
	m.Name = val
}

// GetTunnelId returns the TunnelId property
func (m Device) GetTunnelId() int64 {
	return m.TunnelId
}

// SetTunnelId sets the TunnelId property
func (m *Device) SetTunnelId(val int64) {
	m.TunnelId = val
}
