// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// Tunnel is an object.
type Tunnel struct {
	// DeviceIds:
	DeviceIds []int64 `json:"deviceIds,omitempty" mapstructure:"deviceIds,omitempty"`
	// Id:
	Id int64 `json:"id,omitempty" mapstructure:"id,omitempty"`
	// Kind:
	Kind string `json:"kind,omitempty" mapstructure:"kind,omitempty"`
	// Name:
	Name string `json:"name" mapstructure:"name"`
}

// Validate implements basic validation for this model
func (m Tunnel) Validate() error {
	return validation.Errors{
		"deviceIds": validation.Validate(
			m.DeviceIds,
		),
	}.Filter()
}

// GetDeviceIds returns the DeviceIds property
func (m Tunnel) GetDeviceIds() []int64 {
	return m.DeviceIds
}

// SetDeviceIds sets the DeviceIds property
func (m *Tunnel) SetDeviceIds(val []int64) {
	m.DeviceIds = val
}

// GetId returns the Id property
func (m Tunnel) GetId() int64 {
	return m.Id
}

// SetId sets the Id property
func (m *Tunnel) SetId(val int64) {
	m.Id = val
}

// GetKind returns the Kind property
func (m Tunnel) GetKind() string {
	return m.Kind
}

// SetKind sets the Kind property
func (m *Tunnel) SetKind(val string) {
	m.Kind = val
}

// GetName returns the Name property
func (m Tunnel) GetName() string {
	return m.Name
}

// SetName sets the Name property
func (m *Tunnel) SetName(val string) {
	m.Name = val
}
