// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestDeviceCategory_Validate(t *testing.T) {
	tests := []struct {
		name      string
		m         DeviceCategory
		assertion assert.ErrorAssertionFunc
	}{
		{
			name:      "valid device category",
			m:         ValidDevice.Category,
			assertion: assert.NoError,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.assertion(t, tt.m.Validate())
		})
	}
}
