// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestDeleteDeviceQueryParameters_Validate(t *testing.T) {
	tests := []struct {
		name      string
		m         DeleteDeviceQueryParameters
		assertion assert.ErrorAssertionFunc
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.assertion(t, tt.m.Validate())
		})
	}
}

func TestDeleteDeviceQueryParameters_GetApiKey(t *testing.T) {
	tests := []struct {
		name string
		m    DeleteDeviceQueryParameters
		want string
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.m.GetApiKey())
		})
	}
}

func TestDeleteDeviceQueryParameters_SetApiKey(t *testing.T) {
	type args struct {
		val string
	}
	tests := []struct {
		name string
		m    *DeleteDeviceQueryParameters
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.m.SetApiKey(tt.args.val)
		})
	}
}

func TestDeleteDeviceQueryParameters_GetDeviceId(t *testing.T) {
	tests := []struct {
		name string
		m    DeleteDeviceQueryParameters
		want int64
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.m.GetDeviceId())
		})
	}
}

func TestDeleteDeviceQueryParameters_SetDeviceId(t *testing.T) {
	type args struct {
		val int64
	}
	tests := []struct {
		name string
		m    *DeleteDeviceQueryParameters
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.m.SetDeviceId(tt.args.val)
		})
	}
}
