// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Tunnelbot - OpenAPI 3.0
//	Version: 1
package models

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// DeleteDeviceQueryParameters is an object.
type DeleteDeviceQueryParameters struct {
	// ApiKey:
	ApiKey string `json:"api_key,omitempty" mapstructure:"api_key,omitempty"`
	// DeviceId: Device id to delete
	DeviceId int64 `json:"deviceId" mapstructure:"deviceId"`
}

// Validate implements basic validation for this model
func (m DeleteDeviceQueryParameters) Validate() error {
	return validation.Errors{}.Filter()
}

// GetApiKey returns the ApiKey property
func (m DeleteDeviceQueryParameters) GetApiKey() string {
	return m.ApiKey
}

// SetApiKey sets the ApiKey property
func (m *DeleteDeviceQueryParameters) SetApiKey(val string) {
	m.ApiKey = val
}

// GetDeviceId returns the DeviceId property
func (m DeleteDeviceQueryParameters) GetDeviceId() int64 {
	return m.DeviceId
}

// SetDeviceId sets the DeviceId property
func (m *DeleteDeviceQueryParameters) SetDeviceId(val int64) {
	m.DeviceId = val
}
